### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by bijubjs** [filipematias23/cleanRfield#3]
I tried to install the package. But an error message as below:

ERROR: dependency ‘rgdal’ is not available for package ‘cleanRfield’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/cleanRfield’
Warning messages:
1: In i.p(...) : installation of package ‘rgdal’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/5_/74nhx31d521cjc_gjz58nh8r0000gn/T//RtmpNMRAD1/file200245c2e6b0/cleanRfield_0.0.1.tar.gz’ had non-zero exit status

My R version is 2021.09.0 Build 351. I am using Mac with macOS 12.3.1 (21E258).

R version: RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by biju9bjs** [comment]
How can I install c libraries in mac?

**Comment by nfahlgren** [comment]
I believe GDAL would either need to be compiled from source or you could use conda to install a precompiled package for macOS. https://gdal.org/index.html
